#include <utility>
#include <asio.hpp>
#include <thread>
#include <vector>
#include "utils/logger.hpp"
#include "storage/hash_table.hpp"
#include "message.pb.h" // File generated by Protobuf

using asio::ip::tcp;

inline std::string get_tid()
{
    std::stringstream ss;
    ss << std::this_thread::get_id();
    return ss.str();
}

// Função auxiliar para processar cada cliente individualmente
void handle_client(tcp::socket socket, kv_store::storage::HashTable &storage, const std::string &dump_file)
{
    try
    {
        asio::streambuf receive_buffer;
        asio::read_until(socket, receive_buffer, '\n');

        std::string raw_request;
        std::istream is(&receive_buffer);
        std::getline(is, raw_request);

        kv_store::network::KVRequest request;
        if (request.ParseFromString(raw_request))
        {
            kv_store::network::KVResponse resp;

            if (request.type() == kv_store::network::KVRequest::SET)
            {
                storage.set(request.key(), request.value());
                storage.save_to_file(dump_file);
                resp.set_success(true);
                resp.set_message("Key stored and persisted (Thread-Safe)");
                LOG_INFO("Thread [{}] - SET key='{}'", get_tid(), request.key());
            }
            else if (request.type() == kv_store::network::KVRequest::GET)
            {
                auto val = storage.get(request.key());
                if (val)
                {
                    resp.set_success(true);
                    resp.set_value(*val);
                    resp.set_message("Key found");
                }
                else
                {
                    resp.set_success(false);
                    resp.set_message("Key not found");
                }
                LOG_INFO("Thread [{}] - GET key='{}'", get_tid(), request.key());
            }

            std::string out;
            resp.SerializeToString(&out);
            out += "\n";
            asio::write(socket, asio::buffer(out));
        }
    }
    catch (const std::exception &e)
    {
        LOG_ERROR("Client session error: {}", e.what());
    }
    // O socket é fechado automaticamente aqui ao sair do escopo
}

int main()
{
    kv_store::utils::init_logging();
    kv_store::storage::HashTable storage;
    const std::string dump_file = "storage_dump.kv";

    if (storage.load_from_file(dump_file))
    {
        LOG_INFO("Database recovery successful from {}", dump_file);
    }

    try
    {
        asio::io_context io_context;
        tcp::acceptor acceptor(io_context, tcp::endpoint(tcp::v4(), 8080));

        LOG_INFO("Multi-threaded KV-Store server running on port 8080...");

        for (;;)
        {
            tcp::socket socket(io_context);
            acceptor.accept(socket); // O servidor para aqui até alguém conectar

            LOG_INFO("New connection accepted. Dispatching thread...");

            // DISPATCH: Cria uma thread para o cliente e volta imediatamente para o accept()
            // Usamos std::ref(storage) para passar a referência segura entre threads
            std::thread t(handle_client, std::move(socket), std::ref(storage), dump_file);

            // Detach permite que a thread rode sozinha e se limpe ao terminar
            t.detach();
        }
    }
    catch (const std::exception &e)
    {
        LOG_ERROR("Server critical error: {}", e.what());
    }

    return 0;
}