#include <utility>
#include <asio.hpp>
#include "utils/logger.hpp"
#include "storage/hash_table.hpp"
#include "message.pb.h" // File generated by Protobuf

using asio::ip::tcp;

int main()
{
    kv_store::utils::init_logging();
    // The core of our database
    kv_store::storage::HashTable storage;

    try
    {
        asio::io_context io_context;
        tcp::acceptor acceptor(io_context, tcp::endpoint(tcp::v4(), 8080));

        LOG_INFO("KV-Store server running on port 8080...");
        LOG_INFO("Awaiting client connections...");

        for (;;)
        {
            tcp::socket socket(io_context);
            acceptor.accept(socket);

            LOG_INFO("Client connected: {}", socket.remote_endpoint().address().to_string());

            // Professional Tip: Ensure the message matches the size the client expects
            // "Welcome to KV-Store Distributed!" has 33 chars + \n = 34 bytes
            // std::string msg = "Welcome to KV-Store Distributed!\n";
            asio::streambuf receive_buffer;
            asio::read_until(socket, receive_buffer, '\n');

            std::string raw_request;
            std::istream is(&receive_buffer);
            std::getline(is, raw_request);

            kv_store::network::KVRequest request;
            if (request.ParseFromString(raw_request))
            {
                if (request.type() == kv_store::network::KVRequest::SET)
                {
                    storage.set(request.key(), request.value());

                    // Respond success
                    kv_store::network::KVResponse resp;
                    resp.set_success(true);
                    resp.set_message("Key stored successfully");

                    std::string out;
                    resp.SerializeToString(&out);
                    out += "\n";
                    asio::error_code ec;
                    asio::write(socket, asio::buffer(out), ec);

                    if (ec)
                    {
                        LOG_ERROR("Failed to send message: {}", ec.message());
                    }
                    else
                    {
                        LOG_DEBUG("Greeting sent successfully.");
                    }
                }
            }


            // The socket will close here when going out of scope.
            // For now it's fine, but in the future we will keep it alive
            // to process multiple commands (SET/GET).
        }
    }
    catch (const std::exception &e)
    {
        LOG_ERROR("Server critical error: {}", e.what());
    }

    return 0;
}