#include <utility>
#include <asio.hpp>
#include "utils/logger.hpp"
#include "storage/hash_table.hpp"
#include "message.pb.h" // File generated by Protobuf

using asio::ip::tcp;

int main()
{
    kv_store::utils::init_logging();

    kv_store::storage::HashTable storage;

    // 1. CARREGAR DADOS EXISTENTES AO INICIAR
    // O ficheiro será criado na pasta onde executas o binário
    const std::string dump_file = "storage_dump.kv";
    if (storage.load_from_file(dump_file))
    {
        LOG_INFO("Database recovery successful. Data loaded from {}", dump_file);
    }
    else
    {
        LOG_INFO("No previous storage data found. Starting with an empty database.");
    }

    try
    {
        asio::io_context io_context;
        tcp::acceptor acceptor(io_context, tcp::endpoint(tcp::v4(), 8080));

        LOG_INFO("KV-Store server running on port 8080...");

        for (;;)
        {
            tcp::socket socket(io_context);
            acceptor.accept(socket);

            asio::streambuf receive_buffer;
            asio::read_until(socket, receive_buffer, '\n');

            std::string raw_request;
            std::istream is(&receive_buffer);
            std::getline(is, raw_request);

            kv_store::network::KVRequest request;
            if (request.ParseFromString(raw_request))
            {
                kv_store::network::KVResponse resp;

                if (request.type() == kv_store::network::KVRequest::SET)
                {
                    storage.set(request.key(), request.value());

                    // 2. PERSISTÊNCIA IMEDIATA
                    // Salva em disco sempre que houver uma alteração
                    storage.save_to_file(dump_file);

                    resp.set_success(true);
                    resp.set_message("Key stored and persisted to disk");
                    LOG_INFO("Operation: SET key='{}' (Persisted)", request.key());
                }
                else if (request.type() == kv_store::network::KVRequest::GET)
                {
                    auto val = storage.get(request.key());
                    if (val)
                    {
                        resp.set_success(true);
                        resp.set_value(*val);
                        resp.set_message("Key found");
                    }
                    else
                    {
                        resp.set_success(false);
                        resp.set_message("Key not found");
                    }
                    LOG_INFO("Operation: GET key='{}'", request.key());
                }

                // Envio da resposta...
                std::string out;
                resp.SerializeToString(&out);
                out += "\n";
                asio::write(socket, asio::buffer(out));
            }
        }
    }
    catch (const std::exception &e)
    {
        LOG_ERROR("Server critical error: {}", e.what());
    }

    return 0;
}